
name: CI

on:
  push:
    branches: 
      - '**'  
jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2    
    - run: cd /src/sample-solution
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - uses: /
